---

- name: Rolling out common configuration on all hosts
  hosts: all
  become: true
  gather_facts: yes
  
  roles:
   - common

- name: Installing ELK-Sankey Platform (Elasticsearch server instance)
  hosts: elasticsearch-server
  gather_facts: yes
  become: true

  roles:
   - elasticsearch
   - data-generation

- name: Installing ELK-Sankey Platform (kibana - resides on the elasticsearch server)
  hosts: kibana-server
  gather_facts: yes
  become: true
  
  roles:
   - kibana
