---

- name: Rolling out common configuration
  hosts: all
  become: true
  
  roles:
   - common

- name: Installing ELK-Sankey Platform (Elasticsearch)
  hosts: elasticsearch
  gather_facts: yes
  become: true

  roles:
   - elasticsearch

- name: Installing ELK-Sankey Platform (kibana - resides on the elasticsearch server)
  hosts: kibana
  gather_facts: yes
  become: true

  roles:
   - kibana

- name: Installing ELK-Sankey Platform (Filebeat - resides on the collection endpoint system)
  hosts: filebeat
  gather_facts: yes
  become: true

  roles:
   - filebeat
