---
# tasks file for data-generation

- name: Installing rpm
  package:
   name: npm
   state: latest
   
- name: Installing makelogs utility for some test data
  shell: npm install -g @elastic/makelogs

- name: Generating data
  shell: /usr/local/bin/makelogs --host 
