---
# tasks file for data-generation

- name: Installing rpm
  package:
   name: npm
   state: latest
   
- name: Installing makelogs utility for some test data
  shell: npm install -g @elastic/makelogs

- name: Generating makelog data
  shell: /usr/local/bin/makelogs --host "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9200"
