---
# tasks file for elasticsearch

- name: Installing elasticsearch
  package:
   name: elasticsearch 
   state: latest

- name: Opening up the firewall for kibana 
  firewalld:
   zone: public
   port: 9200/tcp
   permanent: true
   state: enabled
   immediate: true
  become: yes

- name: Starting ES
  service: 
   name: elasticsearch
   state: started
