---
# tasks file for kibana
- name: Installing kibana
  package:
   name: kibana 
   state: latest
   
- name: Opening up the firewall for kibana 
  firewalld:
   zone: public
   port: 5601/tcp
   permanent: true
   state: enabled
   immediate: true
  become: yes

- name: Copying in kibana configuration file
  template:
   src: kibana.yml
   dest: /etc/kibana
  notify: restart-kibana

- name: Installing vega plugin
  shell: cd /usr/share/kibana/bin && kibana-plugin https://github.com/nyurik/kibana-vega-vis/releases/download/v1.2.0/vega_vis-1.2.0--for-Kibana-6.2.4.zip 

- name: Starting kibana
  service:
   name: kibana
   state: started
