---
# tasks file for kibana
- name: Installing kibana
  package:
   name: kibana 
   state: latest
   
- name: Opening up the firewall for kibana 
  firewalld:
   zone: public
   port: 5601/tcp
   permanent: true
   state: enabled
   immediate: true
  become: yes

- name: Copying in kibana configuration file
  template:
   src: kibana.yml
   dest: /etc/kibana
  notify: restart-kibana

- name: Starting kibana
  service:
   name: kibana
   state: started
